import enum

class CIFType(enum.Enum):
class SectorCode(enum.Enum):
class IndustryID(enum.Enum):
class IndustryHighLevel(enum.Enum):
class CustomerTitle(enum.Enum):
class IdentificationTypeCode1(enum.Enum):
class IdentificationTypeCode2(enum.Enum):
class FicaStatus(enum.Enum):
class CustomerGender(enum.Enum):
class CustomerEmploymentStatus(enum.Enum):
class CustomerPosition(enum.Enum):
class CustomerFrequencyIncome(enum.Enum):
class CustomerEthnicGroup(enum.Enum):
class CustomerHomeLanguage(enum.Enum):
class CustomerEstimatedMonthlyTurnover(enum.Enum):
class CustomerEstTransRandValue(enum.Enum):
class CustomerExpectedSourceOfFunds(enum.Enum):
class CustomerEstCashTransactValue(enum.Enum):
class CustomerExpectedUseOfChannel(enum.Enum):
class CustomerExpectedForeignTransactions(enum.Enum):
class CustomerExpectedForeignCountry(enum.Enum):
class Rm3RiskRating(enum.Enum):
class SuitableContactTime(enum.Enum):
class CustomerNationality(enum.Enum):
class BusinessTypeOfBusiness(enum.Enum):
class PostalCountry(enum.Enum):
class PostalProvince(enum.Enum):
class ResidentialStatusCode(enum.Enum):
